# Generated by Django 4.1.1 on 2022-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file_path', models.FilePathField(path='C:/Users/vivek/IdeaProjects/assign4')),
            ],
        ),
    ]
