# Generated by Django 4.1.1 on 2022-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='xml_file_path',
            field=models.FilePathField(path='C:/Users/vivek/IdeaProjects/untitled'),
        ),
    ]
