# Generated by Django 4.1.1 on 2022-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_apimodel_xml_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='xml_file_path',
            field=models.FilePathField(path='C:/xmls'),
        ),
    ]
