# Generated by Django 4.1.1 on 2022-09-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_apimodel_xml_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='xml_file_path',
            new_name='xml_file',
        ),
    ]
